on:
  push:
    branches: main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: ls -lah
      - run: make
      - run: ./run.sh
